apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: mysql-sts
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-sts
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: MTIzNDU2
  username: cm9vdA==
#user/pass=root/123456
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sts
spec:
  serviceName: "mysql"
  replicas: 1
  volumeClaimTemplates:
  - metadata:
      name: mysql-local-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "nfs"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 25Gi
  selector:
    matchLabels:
       app: mysql-sts
  template:
    metadata:
     labels:
       app: mysql-sts
    spec:
      containers:
      - image: mysql:5.7.34
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        #- name: SECRET_USERNAME
        #  valueFrom:
        #  secretKeyRef:
        #    name: mysecret
        #    key: username
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-local-storage
          readOnly: false
          mountPath: /var/lib/mysql
