apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: nfs1
#   annotations:
#    hitachi.io/note: "pvc-sample"
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 5Gi
   storageClassName: nfs
---
kind: Pod
apiVersion: v1
metadata:
  name: nfs-test
spec:
  containers:
    - name: my-busybox
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: sample-volume
      command: ["sleep", "1000000"]
      imagePullPolicy: IfNotPresent
  volumes:
    - name: sample-volume
      persistentVolumeClaim:
        claimName: nfs1
